name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build the docs
            os: ubuntu-latest
            python: 3.9
            toxenv: build_docs

          - name: Python 3.9 with full coverage
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-cov

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: python -m pip install --upgrade tox
      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}
      - name: Upload coverage to codecov
        if: contains(matrix.toxenv,'-cov')
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml

    scripts:
      name: ${{ matrix.name }}
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          include:
            - name: Download PS1
              os: ubuntu-latest
              python: 3.9
              script: lcdata_download_ps1

            - name: Download PLAsTiCC
              os: ubuntu-latest
              python: 3.9
              script: lcdata_download_plasticc

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python }}
        - name: Install the package
          run: pip install .
        - name: Run the script
          run: ${{ matrix.script }}